### ISSUE TITLE
Functions requiring row and column names should assume that rownames = colnames.

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#119]
Some functions, e.g. `life_expect`, require that the row names and column names be identical.
The `Rcompadre` matrix accessor functions (`matA`, `matU` etc.) only provide matrices with the column names. 
These are (e.g.) `A1, A2, A3 ...` for the A matrix, and `U1, U2, U3 ...` for the U matrix and so on.

I think we should force Rage functions to assume that the matrices provided to them have colnames == rownames (including non-COMPADRE/COMADRE ones). 

Something like this would work I think:
```
#. If there are no rownames or colnames, make them arbitrarily start with X.
if(all(is.null(rownames(mat_u)), is.null(colnames(mat_u)))){
  rownames(mat_u) <- colnames(mat_u) <- paste0("X",1:nrow(mat_u))
}

#. If there are no rownames, but there are colnames, make rownames <- colnames
if(all(is.null(rownames(mat_u)), !is.null(colnames(mat_u)))){
  rownames(mat_u) <- colnames(mat_u) 
}

#. If there are no colnames, but there are rownames, make colnames <- rownames
if(all(!is.null(rownames(mat_u)), is.null(colnames(mat_u)))){
  rownames(mat_u) <- colnames(mat_u) 
}
```

**Comment by wpetry** [comment]
I put a check function in `utils.R` that tries to get at this earlier in the retreat. It allows row/colnames to be NULL provided that both are. The generalization that's important is to make sure row/colnames match across matrices (plural) provided by the user (i.e., `matU` and `matF` need matching names). There's probably lots of room for improvement on this function, and it could be better incorporated throughout the package. Direct link:

https://github.com/jonesor/Rage/blob/a2fd5146ddfc5212a8d87c3219b3018d59d26b79/R/utils.R#L31-L46

It sounds like you're also proposing that Rage auto-name unnamed matrices. What's the motivation for this? If we went this route, I'd advocate for functions to throw a warning when adding stage names. I could see this getting annoying given that `Rage` functions almost all ingest the same matrix rather than taking output from other functions as part of a pipeline. I suppose there could be an option to suppress naming warnings? Alternatively, we could add a user-facing utility function that adds names to stages (see below). Seems like a lot of overhead, but maybe I'm missing the intended payoff.

```
addStageNames <- function(mat, prefix = "X", overwrite = FALSE){
    # do checks on arguments
    # ...fail if checkMatchingStageNames errors
    # ...fail if mat is not square
    if (isFALSE(overwrite) & !isNULL(rownames(mat))} {
        warning("Matrix already has valid stage names. Set 'overwrite = TRUE' to change to auto-generated names.")
    } else {
        stagenames <- paste0(prefix, 1:nrow(mat))
        rownames(mat) <- stagenames
        colnames(mat) <- stagenames
    }
    return(mat)
```

**Comment by jonesor** [comment]
I would like to stop this annoying behaviour when using data direct from COMPADRE/COMADRE:

```
> library(tidyverse)
> library(Rcompadre)
> library(Rage)
> 
> com <- cdb_fetch("comadre")
This is COMADRE version 4.21.1.0 (release date Jan_25_2021)
See user agreement at https://www.compadre-db.org/Page/UserAgreement
> Rage::life_expect(matA(com)[[100]])
Error in checkMatchingStageNames(matU) : 
  When naming lifestages, both rows and columns must be named and their names must be identical
> 
```

Right now `Rcompadre::matA` (etc.) produces lists of matrices that have column names that are defined by their matrix type and numeric position (`A1, A2, A3...` for the A matrix). 
This is something that we could fix in the `Rcompadre` package.

**Comment by jonesor** [comment]
This is now resolved I think. I have modified the `ClassUnionMethods.R` functions in `Rcompadre` so that the accessor functions apply the names to both rows and columns. Now the issue here would only apply to non-COM(P)ADRE matrices, which I think is fine probably.

**Comment by jonesor** [comment]
I'm closing this now, since it is no longer a problem after updating the `Rcompadre` `ClassUnionMethods`
