### ISSUE TITLE
Change makeLifeTable so that it returns a list object that includes a life table.

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#12]
`makeLifeTable` currently returns a list object with numerous vectors.
Most of these are the constituent columns of a life table, with the addition of `R0Fec` and  something called `TcFec`.
I think that the object returned should be a list object with a data.frame (the life table) and the other two statistics (R0...).

In addition, the description (Rd file) should be updated - it is not correct as it stands.

**Comment by iainmstott** [comment]
I'm just working with this and was surprised that it's a list.

I don't see any reason to include the other stats, cant it be the case that (like with survival and lifetime reproductive events) be shopped out to another function? That way the makeLifeTable function really just returns a life table.

(I can do this if needs be)

**Comment by jonesor** [comment]
I agree. Lets ship out those stats to another function.
Could you do it?



On 28 June 2018 at 15.36.12, Iain Stott (notifications@github.com) wrote:

I'm just working with this and was surprised that it's a list.

I don't see any reason to include the other stats, cant it be the case that
(like with survival and lifetime reproductive events) be shopped out to
another function? That way the makeLifeTable function really just returns a
life table.

(I can do this if needs be)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jonesor/Rage/issues/12#issuecomment-401036981>, or mute
the thread

**Comment by patrickbarks** [comment]
I have a pull request (#18) that includes lots of edits to `makeLifeTable`, that @jonesor said he will review soon. To avoid conflicts, perhaps I could add a commit to remove the R0 and Tc calculations and just return the life table data frame, and @iainmstott could create new functions for R0 and Tc?

On a related note, I think both R0 and Tc can be calculated either from a matrix or from a life table, and the intepretation differs between the two approaches if offspring can arise in more than 1 stage class (Caswell 2001 s. 5.3.4 and 5.3.5). Our current 'matrix version' of R0 doesn't deal well with this.

For stage-classified models Caswell (p. 128) seems to recommend the calculation:

```
R <- matF %*% N # where N is the fundamental matrix
R0 <- max(Re(eigen(R)$values))
```

whereas our current calculation is:

```
R <- matF %*% N
R0 <- R[startLife, startLife]
```

The two are the same if offspring only arise in stage startLife, but otherwise differ (only the former is affected by the production of offspring in any stage other than startLife).

My opinion is that we should change `Rage::R0` to use the eigenvalue method, and add a new function for the matrix version of `Tc` (= log R0 / log lambda), and perhaps not include the life table version of either R0 or Tc.

**Comment by jonesor** [comment]
I have merged @patrickbarks changes now.

**Comment by iainmstott** [comment]
I can create the extra functions 👍🏻

I can't decide whether it would be a good idea to offer people different methods, or to choose one and roll with it. For many of these functions, there will be a matrix option and a life table option (e.g. life expectancy). The package is after all called Rage, so we can't avoid life tables. 

I'd probably advocate one function which takes both a matrix and a life table (whether generated using Rage or not), which does a different calculation depending on the input.

**Comment by jonesor** [comment]
Yep - go ahead! I agree that a single function would be best.

**Comment by patrickbarks** [comment]
I think this general issue applies to a few of the Rage functions (`lifeTimeRepEvents`, `longevity`, `qsdConverge`). My initial thought is that it would be preferable to keep the output in the same time units as the input matrices, and leave it to the user to subsequently scale the results by AnnualPeriodicity if so desired (/if appropriate). Whether to compare demographic traits across matrices with differing AnnualPeriodicity is potentially a difficult decision best left to the user, and I worry that our imposing a standard time unit on the output might give the impression that all rows of the db are inherently comparable.

**Comment by jonesor** [comment]
Closing - `mpm_to_table` does this.
We can revisit any remaining issues (i.e. regarding the projection interval) at a later date.
