### ISSUE TITLE
Make descriptions of matrices (matU, matF, matC and matA) consistent across documentation 

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#7]
Descriptions of matrices should be made consistent across all functions.

**Comment by patrickbarks** [comment]
How about these?

`matA` A matrix population model (i.e. a square projection matrix)


`matU` The survival component of a matrix population model (i.e. a square projection matrix reflecting survival-related transitions; e.g. progression, stasis, and retrogression)

`matF` The sexual component of a matrix population model (i.e. a square projection matrix reflecting transitions due to sexual reproduction)

`matC` The clonal component of a matrix population model (i.e. a square projection matrix reflecting transitions due to clonal reproduction)


`matR` The reproductive component of a matrix population model (i.e. a square projection matrix reflecting transitions due to reproduction; either sexual, clonal, or both)

**Comment by jonesor** [comment]
Perfect.
